{
  "contest": 372,
  "handle": "t0x1c",
  "risk": "2",
  "title": "Failed ERC20 transfer inside `claim()` results in permanent loss of funds",
  "issueId": 54,
  "issueUrl": "https://github.com/code-423n4/2024-04-renzo-validation/issues/54"
}